version: '2'

services:
  app:
    image: 'nicolfo/aw2.g33.lab4'
    ports:
      - "8081:8081"
    expose:
      - "8081"
    build:
      context: .
    container_name: lab4
    depends_on:
      - db
      - keycloak
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - KEYCLOAK_HOST=keycloak


  db:
    image: 'postgres:latest'
    container_name: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
  keycloak:
    image: 'nicolfo/keycloak-lab4'
    container_name: keycloak
    ports:
      - "8080:8080"
    environment:
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KEYCLOAK_ADMIN=admin
    command: start-dev
