PUT 127.0.0.1:8080/API/profiles/prova3@polito.it
content-type: application/json

{
    "email": "prova3@polito.it",
    "name": "prova1"
}

###
POST 127.0.0.1:8080/API/profiles/
content-type: application/json

{
    "email": "prova2@polito.it",
    "name": "prova2"
}

###
GET 127.0.0.1:8080/API/profiles/prova3@polito.it


###